trigger:
 - demo
 - releases/*

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(P12FileName)'# The 'P12FileName' variable is set in the Azure pipelines 'Variables'.
    certPwd: '$(P12Password)' # The 'P12Password' variable is set in the Azure pipelines 'Variables'. and marked 'secret' to be encrypted
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(provProfileSecureFileName)'# The 'provProfileSecureFileName' variable is set in azure pipelines 'Variables'

- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    scheme: 'DemoApp'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    useXcpretty: false
    
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/output/$(SDK)/$(Configuration)'
    artifactName: 'drop'
    artifactType: 'Container'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'AZURE_APPCENTER'
    appSlug: 'https://appcenter.ms/users/yogeshwagh0017-gmail.com/apps/DemoApp'
    appFile: '$(build.artifactStagingDirectory)/output/$(SDK)/$(Configuration)'
    releaseNotesOption: 'input'
    releaseNotesInput: 'test'
    destinationType: 'groups'