
trigger:
 - demo
 - releases/*

pool:
  vmImage: 'macos-latest'

variables:
 p12FileName : '$(P12FileName)'
 p12FilePassword: '$(P12Password)'
 profileName : '$(provProfileSecureFileName)'
 scheme: 'DemoApp'


steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(p12FileName)'# The 'P12FileName' variable is set in the Azure pipelines 'Variables'.
    certPwd: '$(p12FilePassword)' # The 'P12Password' variable is set in the Azure pipelines 'Variables'. and marked 'secret' to be encrypted
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(profileName)'# The 'provProfileSecureFileName' variable is set in azure pipelines 'Variables'

- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    scheme: 'DemoApp'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    useXcpretty: false
    
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'Container'


