pool:
  vmImage: 'macos-latest'

    
steps:

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(P12FileName)'# The 'P12FileName' variable is set in the Azure pipelines pipeline editor and marked 'secret' to be encrypted
    certPwd: '$(P12Password)' # The 'P12Password' variable is set in the Azure pipelines pipeline editor and marked 'secret' to be encrypted
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(provProfileSecureFileName)'

- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    scheme: 'DemoApp'
    packageApp: true
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    useXcpretty: false
    #args: '-archivePath $(agent.buildDirectory)/DemoApp'
    
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)'
    artifactName: 'drop'
    artifactType: 'Container'
